### ISSUE TITLE
ALSA issue "broken pipe"

### ISSUE THREAD

**Issue by Gunstick** [frno7/psgplay#23]
Starts playing nice, then after 23 seconds it exits violently with:

psgplay: error: (null): ALSA snd_pcm_writei failed: -32 Broken pipe

Also leaving the terminal in a bad state.

PS: Wondering how I can make it play without alsa. Maybe adding a feature that an output file of "-" means to dump the wav to stdout, then I can pipe it into any player. Asking psgplay to write to a named pipe does unfortunately not work "Illegal seek".

**Comment by frno7** [comment]
> Starts playing nice, then after 23 seconds it exits violently with: `psgplay: error: (null): ALSA snd_pcm_writei failed: -32 Broken pipe`

What kind of ALSA device is that? Is it misbehaving, since the receiving end closes it?

> Also leaving the terminal in a bad state.

Yeah, it panics...

> PS: Wondering how I can make it play without alsa. Maybe adding a feature that an output file of "-" means to dump the wav to stdout, then I can pipe it into any player. Asking psgplay to write to a named pipe does unfortunately not work "Illegal seek".

Like this? :-)

https://github.com/frno7/psgplay/blob/f44740e406065024043a5e96f0670c64a6455081/lib/example/example-play.c#L3-L8

**Comment by Gunstick** [comment]
Yes my alsa is really borked. aplay even does not work, but vlc is fine, so I pipe all into cvlc. After a magical "make all" and adding .local to my LD_LIBRARY_PATH the example-play works:

`lib/psgplay/example-play example.sndh | cvlc --demux=rawaud --rawaud-channels 2 --rawaud-samplerate 44100 -`

Thanks for pointing me to the existance of the examples.

**Comment by frno7** [comment]
> Yes my alsa is really borked. aplay even does not work, but vlc is fine, so I pipe all into cvlc. After a magical "make all" and adding .local to my LD_LIBRARY_PATH the example-play works: `lib/psgplay/example-play example.sndh | cvlc --demux=rawaud --rawaud-channels 2 --rawaud-samplerate 44100 -`

Try changing `LIBPSGPLAY_SHARED` to `LIBPSGPLAY_STATIC` here:

https://github.com/frno7/psgplay/blob/f44740e406065024043a5e96f0670c64a6455081/lib/example/Makefile#L43

Then do `make clean` followed by `make -j64 HOST_CFLAGS=-static lib/example/example-play`, and you should obtain this:

```
% ldd lib/example/example-play
	not a dynamic executable
```

No need for `LD_LIBRARY_PATH` anymore. :-) The reason the examples link with the shared library by default is to test that it works. The `psgplay` program itself links with the static library:

https://github.com/frno7/psgplay/blob/f44740e406065024043a5e96f0670c64a6455081/system/unix/Makefile#L55

> Thanks for pointing me to the existance of the examples.

You’re welcome!

**Comment by frno7** [comment]
@Gunstick, would you like to add anything more to this issue?
